### ISSUE TITLE
realm-recyclerview doesn't update itself when an item is inserted from background thread

### ISSUE THREAD

**Issue by puneetagarwal** [bkromhout/realm-recyclerview-lite#12]
Hey @bkromhout , thanks for creating such an awesome library. I am using this library in my code to display emails list. I am using a JobScheduler service to fetch the emails in every 30 seconds. The problem I am facing is that when Realm is updated from the background thread after finishing JobScheduler, the list doesn't get updated automatically. 

I noticed that when I scroll the list, it updates the list with the item at desired position but without scrolling or without closing the Activity and relaunch it, it doesn't update the list automatically.

How can I solve this problem?

Thanks

**Comment by bkromhout** [comment]
Hi @puneetagarwal, glad you're enjoying the library!

As for your problem, I've seen it in some of my apps too, but have been unable to fully solve it. It seems to be a combination of Realm's internal notifications not always being fired, and the adapter code not fully comprehending when it needs to trigger an update.

I can't do much about the former since it's on Realm's side, but for the latter, all I can really advise is to make sure that your model objects correctly implement the `UIDModel` interface ("correctly" meaning, make sure the method on that interface does indeed return something unique for every unique model object).

It may also be that I need to go back and re-work some of the update code, which I won't have time to do until next week once my school semester is over.

As a final note, unfortunately I don't believe that this library will work 100% how I wish for it to until Realm adds fine-grained notifications (see [realm-java/989](https://github.com/realm/realm-java/issues/989)), which will allow me to (hopefully) not have to use tricks like the `UIDModel` interface and such. Until that time, I think there will always be shortcoming with this library—there's just no way for *everything* to be automatic 😔

**Comment by puneetagarwal** [comment]
Hey @bkromhout, Thank you for your advice. It worked for me. Now I am doing all the realm transactions in the background thread which updates the UI automatically and I debugged my code and found that my UID was not unique sometimes. Thanks for your help.

**Comment by bkromhout** [comment]
@puneetagarwal I'm glad I could help!
